services:
  waves-private-node:
    build: .
    ports:
      - '6869:6869'
  waves-explorer:
    image: wavesplatform/explorer
    ports:
      - '3000:8080'
    environment:
      API_NODE_URL: http://localhost:6869
      NODE_LIST: http://localhost:6869
